[tool.black]
line-length = 100
target-version = ['py37', 'py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100
no_lines_before=["LOCALFOLDER"]
sections=["FUTURE","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
default_section="THIRDPARTY"
known_first_party="pymine"
length_sort = true
reverse_sort = true
force_sort_within_sections = true

[tool.pytest.ini_options]
addopts = "--full-trace -v"
testpaths = ["tests"]

[tool.poetry]
name = "PyMine"
version = "0.1.0"
description = "The fast and easy to use, moddable, Python based Minecraft server!"
authors = ["PyMine Developers & Contributors"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.7.9"
aiofile = "3.4.0"
aiohttp = "3.7.4"
async-timeout = "3.0.1"
asyncio-dgram = "1.2.0"
attrs = "20.3.0"
caio = "0.7.0"
cffi = "1.14.5"
chardet = "3.0.4"
colorama = "0.4.4"
cryptography = "3.4.6"
gitdb = "4.0.5"
GitPython = "3.1.34"
idna = "3.1"
immutables = "0.15"
multidict = "5.1.0"
mutf8 = "1.0.3"
numpy = "1.20.1"
pycparser = "2.20"
PyYAML = "5.4.1"
smmap = "3.0.5"
typing-extensions = "3.7.4.3"
yarl = "1.6.3"
uvloop = {version = "^0.15.2", optional = true}
prompt-toolkit = "^3.0.16"
classy-json = "^3.0.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.2.2"
sphinx-material = {git = "https://github.com/bashtage/sphinx-material.git"}
sphinx-tabs = "^2.1.0"
bandit = "^1.7.0"
pydocstyle = "^6.0.0"
flake8-bugbear = "^21.4.3"
flake8-comprehensions = "^3.5.0"
isort = {git = "https://github.com/PyCQA/isort.git", rev = "289476826d407737bfe41a0131b34f3dea3fb861"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
